apiVersion: v1
kind: Service
metadata:
  name: seguindev-websites
  namespace: development
  labels:
    run: seguindev-websites
spec:
  selector:
    run: seguindev-websites
  type: NodePort
  ports:
    - name: adventurework
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: consultantcompanion
      port: 81
      targetPort: 81
      nodePort: 30081
